import esbuild from "esbuild";
import process from "process";
import path from "path";
import { fileURLToPath } from "url";
import builtins from "builtin-modules";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

// Resolve Node builtins to shims so the bundle works in Obsidian's Electron renderer
const nodeBuiltinsShimPlugin = {
	name: "node-builtins-shim",
	setup(build) {
		const shims = {
			process: path.join(__dirname, "process-shim.cjs"),
			string_decoder: path.join(__dirname, "string_decoder-shim.cjs"),
		};
		build.onResolve({ filter: /^(process|string_decoder)\/?$/ }, (args) => {
			const name = args.path.replace(/\/$/, "");
			const shimPath = shims[name];
			if (shimPath) return { path: shimPath };
			return null;
		});
	},
};

// External builtins except those we provide shims for
const SHIMMED_BUILTINS = new Set(["process", "string_decoder"]);
const externalBuiltins = Array.isArray(builtins)
	? builtins.filter((m) => !SHIMMED_BUILTINS.has(m))
	: [...Object.keys(builtins)].filter((m) => !SHIMMED_BUILTINS.has(m));

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	plugins: [nodeBuiltinsShimPlugin],
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...externalBuiltins,
	],
	platform: "node",
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
